version: '3.8'

services:
  # Serviço que envia os dados
  producer:
    build: .
    container_name: producer
    ports:
      - "5050:5000" # Mapeia a porta para você acessar no navegador
    volumes:
      - .:/app # Sincroniza seus arquivos locais com o container
    command: python producer.py

  # Serviço que processa e salva os dados no Data Lake
  consumer:
    build: .
    container_name: consumer
    depends_on:
      - producer # Garante que o producer suba primeiro
    volumes:
      - .:/app # Permite que o consumer salve os arquivos .parquet na sua pasta local
    command: python consumer.py